name = "lean-minimizer"
version = "0.1.0"
defaultTargets = ["minimize"]
testDriver = "test"

[[lean_lib]]
name = "LeanMinimizer"

[[lean_lib]]
name = "LeanMinimizerTest"
globs = ["LeanMinimizerTest.Component.*", "LeanMinimizerTest.CLI.*"]

[[lean_exe]]
name = "minimize"
root = "Main"
# needed for in-process compilation testing
supportInterpreter = true

[[lean_exe]]
name = "test"
root = "Test"
supportInterpreter = true
